# Generated by Django 3.2.4 on 2021-06-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='Грейд')),
            ],
            options={
                'verbose_name': 'грейд',
                'verbose_name_plural': 'Грейды',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('position', models.CharField(max_length=70, verbose_name='Должность')),
                ('employment_date', models.DateField(verbose_name='Дата трудоустройства')),
                ('wage', models.PositiveSmallIntegerField(verbose_name='Оклад')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='staff.gradeposition', verbose_name='Грейд')),
                ('staffs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.staff', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_wage', models.DateField(verbose_name='Дата начисления ЗП')),
                ('sum_wage', models.PositiveSmallIntegerField(verbose_name='Сумма ЗП')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wages', to='staff.staff', unique_for_date='date_wage')),
            ],
            options={
                'verbose_name': 'Заработная плата',
                'verbose_name_plural': 'заработная плата',
            },
        ),
    ]
