# Generated by Django 3.2.4 on 2021-06-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210608_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='positions',
            field=models.CharField(max_length=50, unique=True, verbose_name='Должность'),
        ),
    ]
